name: Build SAMP APK

on:
  push:
    branches: [ "main" ] # Mude para 'master' se for o caso
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # Ou 'temurin'
          java-version: '17' # Verifique se sua source pede Java 11 ou 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: samp-mobile-release
          path: app/build/outputs/apk/release/*.apk
