name: Build SAMP APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Listar Arquivos (Para Debug)
        run: ls -R # Isso vai mostrar no log onde estão seus arquivos se der erro de novo

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          # Removi a linha de cache que causava o erro de 'No file found'

      - name: Make Gradle Executable
        run: |
          # Procura o gradlew em qualquer pasta e dá permissão
          find . -name "gradlew" -exec chmod +x {} +

      - name: Build APK
        # O command 'assembleDebug' tenta compilar mesmo que esteja em subpasta
        run: ./gradlew assembleDebug --stacktrace || find . -name "gradlew" -exec {} assembleDebug --stacktrace \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SAMP-Launcher-APK
          path: "**/*.apk" # Pega qualquer APK gerado em qualquer pasta
